### ISSUE TITLE
(NameError) uninitialized constant Timeout on running plugin.

### ISSUE THREAD

**Issue by kazup0n** [eratostennis/embulk-output-vertica#29]
NameError occurs on running the plugin.
Maybe  `require 'timeout'` is required in `output_thread.rb`

Here's my config and console output.

```
in:
  type: file
  path_prefix: ./embulk-example/csv/sample_
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
out: {type: vertica}
```

```
2016-05-06 15:02:15.973 +0900: Embulk v0.8.8

*** LOCAL GEMS ***

embulk-output-vertica (0.7.3)
jar-dependencies (0.2.3)
jdbc-vertica (0.0.3)
jruby-openssl (0.9.15 java)
json (1.8.0 java)
jvertica (0.2.4)
minitest (5.4.1)
power_assert (0.2.3)
psych (2.0.15 java)
racc (1.4.13 java)
rake (10.1.0)
rdoc (4.1.2)
test-unit (3.0.3)
thread_safe (0.3.5 java)
tzinfo (1.2.2)
```

```
NameError: uninitialized constant Timeout
     const_missing at org/jruby/RubyModule.java:3212
   <class:Vertica> at /Users/kazup0n/.embulk/jruby/2.2.0/gems/embulk-output-vertica-0.7.3/lib/embulk/output/vertica/output_thread.rb:7
   <module:Output> at /Users/kazup0n/.embulk/jruby/2.2.0/gems/embulk-output-vertica-0.7.3/lib/embulk/output/vertica/output_thread.rb:5
   <module:Embulk> at /Users/kazup0n/.embulk/jruby/2.2.0/gems/embulk-output-vertica-0.7.3/lib/embulk/output/vertica/output_thread.rb:4
             <top> at /Users/kazup0n/.embulk/jruby/2.2.0/gems/embulk-output-vertica-0.7.3/lib/embulk/output/vertica/output_thread.rb:3
           require at org/jruby/RubyKernel.java:937
           require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
            (root) at uri:classloader:/jruby/kernel/kernel.rb:1
             <top> at uri:classloader:/jruby/kernel/kernel.rb:13
           require at org/jruby/RubyKernel.java:937
           require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:128
            (root) at /Users/kazup0n/.embulk/jruby/2.2.0/gems/embulk-output-vertica-0.7.3/lib/embulk/output/vertica.rb:3
            (root) at /Users/kazup0n/.embulk/bin/embulk!/embulk/plugin_registry.rb:1
  require_and_show at /Users/kazup0n/.embulk/bin/embulk!/embulk/plugin_registry.rb:81
            search at /Users/kazup0n/.embulk/bin/embulk!/embulk/plugin_registry.rb:39
            lookup at /Users/kazup0n/.embulk/bin/embulk!/embulk/plugin_registry.rb:26
            lookup at /Users/kazup0n/.embulk/bin/embulk!/embulk/plugin.rb:197
   new_java_output at /Users/kazup0n/.embulk/bin/embulk!/embulk/plugin.rb:159
   new_java_output at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/forwardable.rb:183
             <top> at /Users/kazup0n/.embulk/bin/embulk!/embulk/runner.rb:84
           require at org/jruby/RubyKernel.java:937
               run at /Users/kazup0n/.embulk/bin/embulk!/embulk/command/embulk_run.rb:306
             <top> at file:/Users/kazup0n/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51
```
